# List of Ski Resorts
resorts = [
    "49 Degrees North",
    "Afton Alps",
    "Alpenglow",
    "Alpental At The Summit",
    "Alpine Mountain",
    "Alpine Valley",
    "Alpine Valley Resort",
    "Alta",
    "Alta Sierra at Shirley Meadows",
    "Alyeska Resort",
    "Andes Tower Hills Ski Area",
    "Angel Fire Resort",
    "Antelope Butte",
    "Anthony Lakes Mountain Resort",
    "Appalachian Ski Mountain",
    "Apple Mountain",
    "Arapahoe Basin",
    "Arctic Valley",
    "Arizona Snowbowl",
    "Arrowhead Ski Area",
    "Ascutney Mountain Resort",
    "Aspen",
    "Aspen Highlands",
    "Attitash Mountain Resort",
    "Badger Mountain",
    "Bald Mountain",
    "Balsams Wilderness",
    "Bear Creek Ski Area",
    "Bear Mountain",
    "Bear Paw Ski Bowl",
    "Bear Valley",
    "Beaver Creek",
    "Beaver Mountain",
    "Belleayre",
    "Berkshire East",
    "Big Bear Mountain",
    "Big Boulder",
    "Big Creek Ski Area",
    "Big Horn Ski Resort",
    "Big Powderhorn Mountain",
    "Big Sky",
    "Big Tupper Ski Area",
    "Bigrock Ski Area",
    "Bittersweet Ski Area",
    "Black Mountain",
    "Black Mountain of Maine",
    "Black River Basin",
    "Blacktail Mountain Ski Area",
    "Blandford Ski Area",
    "Blue Hills",
    "Blue Knob",
    "Blue Marsh",
    "Blue Mountain Resort",
    "Bluewood",
    "Bogus Basin",
    "Bolton Valley Resort",
    "Boreal Mountain",
    "Boston Mills Brandywine",
    "Bottineau Winter Park",
    "Bousquet Ski Area",
    "Boyce Park",
    "Boyne Mountain",
    "Bradford Ski Area",
    "Brandywine",
    "Brantling Ski Slopes",
    "Breckenridge",
    "Bretton Woods",
    "Brian Head Resort",
    "Bridger Bowl",
    "Brighton Resort",
    "Bristol Mountain",
    "Bromley Mountain",
    "Bruce Mound",
    "Brundage Mountain Resort",
    "Bryce Resort",
    "Buck Hill",
    "Buena Vista",
    "Buffalo Ski Club",
    "Burke Mountain",
    "Buttermilk",
    "Caberfae Peaks",
    "Camden Snow Bowl",
    "Camelback Ski Area",
    "Camp 10 Ski n Snowboard",
    "Campgaw Mountain",
    "Canaan Valley Resort",
    "Cannon Mountain",
    "Cannonsburg",
    "Cascade Mountain",
    "Cataloochee",
    "Catamount Ski and Ride Area",
    "Catamount Ski Area",
    "Chestnut Mountain",
    "China Peak",
    "Christie Mountain",
    "Christmas Mountain",
    "Clear Fork",
    "Cloudmont",
    "Cochran",
    "Cockaigne Ski Area",
    "Coffee Mill",
    "Cooper Spur",
    "Copper Mountain",
    "Coppervale",
    "Cottonwood Butte",
    "Cranmore Mountain Resort",
    "Crested Butte",
    "Crotched Mountain",
    "Crystal Mountain",
    "Crystal Mountain Michigan",
    "Cuchara Mountain",
    "Dartmouth Skiway",
    "Deer Mountain",
    "Deer Valley",
    "Devils Head",
    "Diamond Peak",
    "Discovery Ski Area",
    "Dodge Ridge",
    "Donner Ski Ranch",
    "Dry Hill Ski Area",
    "Durango Mountain Resort",
    "Eagle Point Resort",
    "Eagle Rock",
    "Eaglecrest Ski Area",
    "Eaton Mountain",
    "Echo Mountain",
    "Eldora Mountain Resort",
    "Elk Meadows",
    "Elk Mountain Ski Resort",
    "Elk Ridge Ski and Outdoor Recreation",
    "Elm Creek Winter Recreation Area",
    "Enchanted Forest Cross Country Ski Area",
    "Ferguson Ridge",
    "Fernwood",
    "Four Lakes",
    "Four Seasons",
    "Fun Valley",
    "Giants Ridge Resort",
    "Gladstone Sport Park",
    "Gore Mountain",
    "Grand Geneva",
    "Grand Targhee",
    "Granite Gorge Ski Area",
    "Granite Peak Ski Area",
    "Granlibakken",
    "Great Bear Ski Valley",
    "Great Divide",
    "Greek Peak",
    "Gunstock",
    "Hanson Hills",
    "Hawksnest",
    "Haystack",
    "Heavenly",
    "Hesperus",
    "Hickory Hills",
    "Hickory Ski Center",
    "Hidden Valley",
    "Hidden Valley Club",
    "Hidden Valley Ski",
    "High Point Cross Country Ski Center",
    "Highlands of Olympia",
    "Hilltop Ski Area",
    "Hogadon",
    "Holiday Mountain",
    "Holiday Valley",
    "Holimont Ski Area",
    "Homewood Mountain Resort",
    "Hoodoo Ski Area",
    "Howelsen Hill",
    "Huff Hills Ski Resort",
    "Hunter Mountain",
    "Hurricane Ridge",
    "Hyland Ski and Snowboard Area",
    "Irwin Catskiing by Eleven",
    "Jack Frost",
    "Jackson Creek Summit",
    "Jackson Hole",
    "Jay Peak",
    "Jiminy Peak",
    "June Mountain",
    "Kelly Canyon Ski Area",
    "Kendall Mountain",
    "Keystone",
    "Killington",
    "King Pine",
    "Kirkwood",
    "Kissing Bridge",
    "Labrador Mountain",
    "Las Vegas Ski and Snowboard Resort",
    "Little Ski Hill",
    "Little Switzerland",
    "Lookout Pass",
    "Loon Mountain",
    "Lost Trail - Powder Mountain",
    "Lost Valley",
    "Loup Loup",
    "Loveland",
    "Lutsen Mountains",
    "Lyndon Outing Club",
    "Mad River Glen",
    "Mad River Mountain",
    "Magic Mountain (Idaho)",
    "Magic Mountain (Vermont)",
    "Mammoth Mountain",
    "Maple Ski Ridge",
    "Maple Valley",
    "Marquette Mountain",
    "Marshall Mountain Ski Area",
    "Massanutten",
    "Mauna Kea",
    "Maverick Mountain",
    "McCauley Mountain Ski Center",
    "McIntyre Ski Area",
    "Meadowlark Ski Lodge",
    "Middlebury College Snow Bowl",
    "Mission Ridge",
    "Mohawk Mountain",
    "Monarch Ski Area",
    "Mont Ripley",
    "Montage Mountain Resorts",
    "Montana Snowbowl",
    "Moonlight Basin",
    "Mount Baker",
    "Mount Bohemia",
    "Mount Brighton",
    "Mount Crescent",
    "Mount Frontenac",
    "Mount Jefferson",
    "Mount Kato Ski Area",
    "Mount La Crosse",
    "Mount Lemmon Ski Valley",
    "Mount Pleasant",
    "Mount Snow",
    "Mount Southington Ski Area",
    "Mount Sunapee",
    "Mount Tone",
    "Mountain Creek Resort",
    "Mountain High resort",
    "Mt Abram Ski Resort",
    "Mt Ashland",
    "Mt Bachelor",
    "Mt Baldy (California)",
    "Mt Holly",
    "Mt Hood Meadows",
    "Mt Hood Ski Bowl",
    "Mt Peter Ski Area",
    "Mt Rose Ski at Tahoe",
    "Mt Shasta",
    "Mt Spokane Ski and Snowboard Park",
    "Mt Zion",
    "Mt. Holiday Ski Area",
    "Mulligan's Hollow Ski Bowl",
    "Mystic Mountain at Nemacolin Woodlands",
    "Nashoba Valley",
    "New Hermon Mountain",
    "Nordic Mountain",
    "Nordic Valley",
    "Northstar at Tahoe",
    "Norway Mountain",
    "Nubs Nob SA",
    "Oak Mountain",
    "Ober Gatlinburg Ski Resort",
    "Okemo Mountain",
    "Otis Ridge",
    "Otsego Resort",
    "Pajarito Mountain Ski Area",
    "Palisades Tahoe",
    "Palisades Tahoe - Alpine Meadows",
    "Paoli Peaks",
    "Park City",
    "Pats Peak",
    "Pebble Creek Ski Area",
    "Peek'n Peak Resort",
    "Perfect North Slope",
    "Pico Mountain at Killington",
    "Pine Knob",
    "Pine Mountain",
    "Pines Peak",
    "Pleasant Mountain",
    "Pomerelle Mountain Resort",
    "Porcupine Mountain",
    "Powder Mountain",
    "Powder Ridge",
    "Powder Ridge Ski Area",
    "Powderhorn",
    "Powderhouse Hill",
    "Purgatory",
    "Ragged Mountain Resort",
    "Raging Buffalo Snowboard Ski Park",
    "Red Lodge Mountain",
    "Red River",
    "Riverside Hills",
    "Rocky Mountain",
    "Royal Gorge",
    "Royal Mountain",
    "Saddleback",
    "Sandia Peak",
    "Sapphire Valley",
    "Saskadena Six",
    "Sawkill Family Ski Center",
    "Scaly Mountain",
    "Schweitzer Mountain",
    "Selkirk Powder",
    "Seven Oaks",
    "Seven Springs Mt",
    "Shanty Creek",
    "Shawnee Mountain Ski Area",
    "Showdown Ski Area",
    "Sierra at Tahoe",
    "Silver Mountain",
    "Silverton Mountain",
    "Sipapu Ski and Summer Resort",
    "Ski Apache",
    "Ski Beech Mountain Resort",
    "Ski Big Bear",
    "Ski Brule",
    "Ski Butternut",
    "Ski Cooper",
    "Ski Denton",
    "Ski Liberty",
    "Ski Plattekill",
    "Ski Rio",
    "Ski Roundtop",
    "Ski Santa Fe",
    "Ski Sawmill",
    "Ski Snowstar",
    "Ski Sundown",
    "Ski Ward Ski Area",
    "Ski Windham",
    "Sky Valley",
    "Skyline Ski Resort",
    "Sleeping Giant",
    "Smuggler's Notch",
    "Sno Mountain",
    "Snow Creek",
    "Snow King Resort",
    "Snow Ridge",
    "Snow Snake Mountain",
    "Snow Summit",
    "Snow Trails",
    "Snow Valley",
    "Snowbasin",
    "Snowbird",
    "Snowhaven",
    "Snowmass",
    "Snowshoe Mountain Resort",
    "Snowy Range Ski and Recreation Area",
    "Soda Springs",
    "Soldier Mountain",
    "Solitude",
    "SolVista Golf and Ski Ranch (Silver Creek)",
    "Song Mountain",
    "Spirit Mountain",
    "Split Rock",
    "Spout Springs",
    "Spring Mountain Ski Area",
    "Spruce Mountain Ski Slope",
    "Steamboat",
    "Sterling Forest Ski Center",
    "Stevens Pass",
    "Storrs Hill",
    "Stover Mountain Ski Area",
    "Stowe",
    "Stratton Mountain",
    "Sugar Bowl",
    "Sugar Mountain",
    "Sugarbush",
    "Sugarloaf",
    "Sugarloaf Ski Lodge (Michigan)",
    "Summit at Snoqualmie",
    "Sun Valley",
    "Sunburst",
    "Sundance",
    "Sunday River",
    "Sundown Mountain",
    "Sunlight Mountain Resort",
    "Sunrise Park Resort",
    "Sunrise Ski Area",
    "Swain",
    "Swiss Valley",
    "Sylvan Hill",
    "Tahoe Donner",
    "Tamarack",
    "Tanglwood",
    "Taos",
    "Telemark",
    "Telluride",
    "Tenney Mountain",
    "Terry Peak",
    "Teton Pass Ski Area",
    "The Canyons",
    "The Highlands",
    "The Homestead (Michigan)",
    "The Homestead Ski Area",
    "The Quechee Club",
    "The Summit at Snoqualmie",
    "Thunder Ridge",
    "Timber Ridge",
    "Timberline",
    "Timberline Four Seasons",
    "Titcomb Mountain",
    "Titus Mountain",
    "Toggenburg Mountain",
    "Treetops",
    "Trollhaugen",
    "Turner Mountain",
    "Tussey Mountain",
    "Tuxedo Ridge Ski Center",
    "Tyrol Basin",
    "Vail",
    "Villa Olivia",
    "Wachusett Mountain Ski Area",
    "Warner Canyon",
    "Waterville Valley",
    "Welch Village",
    "West Mountain",
    "Whaleback Mountain",
    "White Pass Village",
    "White Pine",
    "Whitecap Mountain",
    "Whiteface Mountain (Lake Placid)",
    "Whitefish Mountain Resort",
    "Whitetail Resort",
    "Wild Mountain Ski and Snowboard Area",
    "Wildcat Mountain",
    "Willamette Pass",
    "Willard Mountain",
    "Williams Ski Area",
    "Wilmot Mountain",
    "Windham Mountain",
    "Winter Park",
    "Wintergreen Resort",
    "Winterplace Ski Resort",
    "Wisp",
    "Wolf Creek Ski Area",
    "Wolf Creek Utah",
    "Wolf Laurel",
    "Wolf Mountain",
    "Wolf Ridge Ski Resort",
    "Woodbury Ski Area",
    "Woods Valley Ski Area",
    "Yawgoo Valley",
    "Yosemite-Badger Pass Ski Area"
]
